fos_rest:
    zone:
        - { path: ^/admin/* }
    view:
        view_response_listener: true
    exception:
        codes:
            App\Exception\NewsletterRegistrationEmailNotUniqueException: 409
