sulu_route:
  mappings:
    App\Entity\Publication:
      generator: schema
      resource_key: !php/const App\Entity\Publication::RESOURCE_KEY
      options:
        route_schema: /{object["title"]}
