sulu_route:
  mappings:
    App\Domain\Entity\Definition:
      generator: schema
      resource_key: !php/const App\Domain\Entity\Definition::RESOURCE_KEY
      options:
        route_schema: /{translator.trans('app.route.lexicon')}/{object['title']}
    App\Domain\Entity\Publication:
      generator: schema
      resource_key: !php/const App\Domain\Entity\Publication::RESOURCE_KEY
      options:
        route_schema: /{translator.trans('app.route.publications')}/{object["title"]}
