sulu_community:
  webspaces:
    petit-astro:
      from: "%env(WEBSITE_EMAIL)%"

      # Maintenance
      maintenance:
        enabled: false
        template: community/maintenance.html.twig

      # Login
      login:
        embed_template: community/login_embed.html.twig
        template: community/login_form.html.twig

      # Registration
      registration:
        email:
          subject: Registration
          user_template: emails/community/registration_email.html.twig
          admin_template: ~
        type: App\Sulu\Community\Form\RegistrationType
        template: community/registration_form.html.twig

      # Confirmation
      confirmation:
        activate_user: true
        auto_login: true
        email: ~
        template: community/confirmation_message.html.twig

      # Completion
      completion: ~

      # Password Forget / Reset
      password_forget:
        email:
          subject: app.emails.community.password_forget.title
          admin_template: ~
          user_template: emails/community/password_forget_email.html.twig
        template: community/password_forget_form.html.twig
        type: App\Sulu\Community\Form\PasswordForgetType
      password_reset:
        auto_login: true
        email: ~
        template: community/password_reset_form.html.twig
        type: App\Sulu\Community\Form\PasswordResetType

      # Profile
      profile:
        type: App\Sulu\Community\Form\ProfileType
        redirect_to: ?send=true
        template: community/profile_form.html.twig

      # Email Confirmation
      email_confirmation:
        email:
          subject: Email Changed
          user_template: emails/community/email_confirmation.html.twig
          admin_template: ~
        template: community/email_confirmation_success.html.twig

      # Blacklist
      blacklisted:
        email: ~
      blacklist_denied:
        email: ~
        template: community/blacklist_denied.html.twig
      blacklist_confirmed:
        email: ~
        template: community/blacklist_confirmed.html.twig
