sulu_admin:
  email: "%env(SULU_ADMIN_EMAIL)%"
  forms:
    directories:
      - "%kernel.project_dir%/config/forms"
  lists:
    directories:
      - "%kernel.project_dir%/config/lists"
  resources:
    definitions:
      routes:
        list: app.admin.get_definition_list
        detail: app.admin.get_definition

  field_type_options:
    selection:
      definition_selection:
        default_type: list_overlay
        resource_key: !php/const App\Entity\Definition::RESOURCE_KEY
        view:
          name: !php/const App\Admin\DefinitionAdmin::EDIT_FORM_VIEW
          result_to_view:
            id: id
        types:
          auto_complete:
            display_property: title
            search_properties:
              - title
          list_overlay:
            adapter: table
            list_key: definitions
            display_properties:
              - title
            label: "app.admin.definition_select"
            icon: fa-book
            overlay_title: "app.admin.definition_selection_overlay_title"

sulu_core:
  locales:
    fr: Français
    en: English
  translations:
    - fr
    - en
