sulu_admin:
  email: "%env(SULU_ADMIN_EMAIL)%"

  forms:
    directories:
      - "%kernel.project_dir%/config/forms"
  lists:
    directories:
      - "%kernel.project_dir%/config/lists"

  resources:
    !php/const App\Entity\ContactRequest::RESOURCE_KEY:
      routes:
        list: app.admin.get_contact_request_list
        detail: app.admin.get_contact_request
    !php/const App\Entity\Definition::RESOURCE_KEY:
      routes:
        list: app.admin.get_definition_list
        detail: app.admin.get_definition
    !php/const App\Entity\NewsletterRegistration::RESOURCE_KEY:
      routes:
        list: app.admin.get_newsletter_registration_list
        detail: app.admin.get_newsletter_registration
    !php/const App\Entity\Publication::RESOURCE_KEY:
      routes:
        list: app.admin.get_publication_list
        detail: app.admin.get_publication
    !php/const App\Entity\PublicationTypo::RESOURCE_KEY:
      routes:
        list: app.admin.get_publication_typo_list
        detail: app.admin.get_publication_typo

  field_type_options:
    selection:
      definitions_selection:
        default_type: list_overlay
        resource_key: !php/const App\Entity\Definition::RESOURCE_KEY
        view:
          name: !php/const App\Sulu\Admin\DefinitionAdmin::EDIT_FORM_VIEW
          result_to_view:
            id: id
        types:
          auto_complete:
            display_property: title
            search_properties:
              - title
          list_overlay:
            adapter: table
            list_key: !php/const App\Entity\Definition::RESOURCE_KEY
            display_properties:
              - title
            label: "app.admin.definition_selection"
            icon: !php/const App\Entity\Definition::RESOURCE_ICON
            overlay_title: "app.admin.definition_selection_overlay_title"
