sulu_admin:
    email: "%env(SULU_ADMIN_EMAIL)%"
    forms:
        directories:
            - "%kernel.project_dir%/config/forms"
    lists:
        directories:
            - "%kernel.project_dir%/config/lists"
    resources:
        definitions:
            routes:
                list: app.admin.get_definition_list
                detail: app.admin.get_definition

sulu_core:
    locales:
        fr: Français
        en: English
    translations:
        - fr
        - en
