sulu_search:
  indexes:
    definition:
      name: app.admin.lexicon
      icon: fa-book
      security_context: !php/const App\Admin\DefinitionAdmin::SECURITY_CONTEXT
      contexts: []
      view:
        name: !php/const App\Admin\DefinitionAdmin::EDIT_FORM_VIEW
        result_to_view:
          id: id
          locale: locale
  website:
    indexes:
      - definition
