sulu_search:
  indexes:
    !php/const App\Domain\Entity\Definition::RESOURCE_KEY:
      name: app.admin.lexicon
      icon: !php/const App\Domain\Entity\Definition::RESOURCE_ICON
      security_context: !php/const App\Infrastructure\Sulu\Admin\DefinitionAdmin::SECURITY_CONTEXT
      contexts: []
      view:
        name: !php/const App\Infrastructure\Sulu\Admin\DefinitionAdmin::EDIT_FORM_VIEW
        result_to_view:
          id: id
          locale: locale
    !php/const App\Domain\Entity\Publication::RESOURCE_KEY:
      name: app.admin.publications
      icon: !php/const App\Domain\Entity\Publication::RESOURCE_ICON
      security_context: !php/const App\Infrastructure\Sulu\Admin\PublicationAdmin::SECURITY_CONTEXT
      contexts: []
      view:
        name: !php/const App\Infrastructure\Sulu\Admin\PublicationAdmin::EDIT_FORM_VIEW
        result_to_view:
          id: id
          locale: locale
  website:
    indexes:
      !php/const App\Domain\Entity\Definition::RESOURCE_KEY: !php/const App\Domain\Entity\Definition::RESOURCE_KEY
      !php/const App\Domain\Entity\Publication::RESOURCE_KEY: publications_published
