version: '3'

services:
  ###> doctrine/doctrine-bundle ###
  database:
    image: mariadb
    environment:
      MARIADB_DATABASE: ${MARIADB_DATABASE:-su_myapp}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD:-root}
      MARIADB_ROOT_HOST: '%'
    volumes:
      - db-data:/var/lib/mysql
      - ./var/docker/db/data:/var/lib/mysql:rw
  ###< doctrine/doctrine-bundle ###

  # http://127.0.0.1:8081/
  adminer:
    image: adminer
    container_name: adminer
    environment:
      ADMINER_DEFAULT_SERVER: database
    depends_on:
      - database
    ports:
      - 8081:8080

volumes:
  ###> doctrine/doctrine-bundle ###
  db-data: ###< doctrine/doctrine-bundle ###
