parameters:
  default_locale: en

services:
  _defaults:
    autowire: true
    autoconfigure: true
    bind:
      "string $kernelEnvironment": "%kernel.environment%"
      "string $projectDir": "%kernel.project_dir%"
      "string $suluContext": "%sulu.context%"
      "string $suluRouteClass": "%sulu.model.route.class%"
      "bool $suluDocumentShowDrafts": "%sulu_document_manager.show_drafts%"

  App\:
    resource: "../src/"
    exclude:
      - "../src/API/"
      - "../src/DependencyInjection/"
      - "../src/Form/Data/"
      - "../src/Manager/Data/"
      - "../src/Entity/"
      - "../src/Event/"
      - "../src/Kernel.php"
      - "../src/Sulu/ActivityEvent/"

  _instanceof:
    Sulu\Bundle\RouteBundle\Routing\Defaults\RouteDefaultsProviderInterface:
      tags:
        - "sulu_route.defaults_provider"
    Sulu\Bundle\ContentBundle\Content\Infrastructure\Sulu\Search\ContentSearchMetadataProvider:
      tags:
        - "massive_search.metadata.provider"

  # Extended sulu MaskConverter with custol permission types
  sulu_security.mask_converter:
    class: App\Sulu\Security\MaskConverter

  Sulu\Twig\Extensions\ImageExtension:
    arguments:
      $defaultAttributes:
        loading: "lazy"
      $defaultAdditionalTypes:
        webp: "image/webp"
      $aspectRatio: true
      $imageFormatConfiguration: "%sulu_media.image.formats%"
