parameters:
  default_locale: en

services:
  _defaults:
    autowire: true
    autoconfigure: true
    bind:
      "string $kernelEnvironment": "%kernel.environment%"
      "string $suluContext": "%sulu.context%"
      "string $suluRouteClass": "%sulu.model.route.class%"
      "bool $suluDocumentShowDrafts": "%sulu_document_manager.show_drafts%"

  App\:
    resource: "../src/"
    exclude:
      - "../src/DependencyInjection/"
      - "../src/Entity/"
      - "../src/Kernel.php"

  _instanceof:
    Sulu\Bundle\RouteBundle\Routing\Defaults\RouteDefaultsProviderInterface:
      tags:
        - "sulu_route.defaults_provider"
    Sulu\Bundle\ContentBundle\Content\Infrastructure\Sulu\Search\ContentSearchMetadataProvider:
      tags:
        - "massive_search.metadata.provider"

  Sulu\Bundle\HeadlessBundle\Controller\HeadlessWebsiteController:
    public: true
  Sulu\Bundle\WebsiteBundle\Controller\DefaultController:
    public: true

  Sulu\Twig\Extensions\ImageExtension:
    arguments:
      $defaultAttributes:
        loading: "lazy"
      $defaultAdditionalTypes:
        webp: "image/webp"
      $aspectRatio: true
      $imageFormatConfiguration: "%sulu_media.image.formats%"
